module.exports.data = {
    currency: 'NGN',
    KYCInformation: {
      address: {
        country: 'NIGERIA',
        state: 'LAGOS',
        city: 'Surulere',
        street: 'Oduselu str',
        zip: '100001',
      },
      document: {
        type: 'International Pass',
        number: '2103822',
        issuedBy: 'SEC',
        issuedDate: '2021-09-05',
        expirationDate: '2022-09-05',
        issuedCountryCode: 'ISO-840',
      },
      firstName: 'Olaitan',
      lastName: 'Samuel',
      businessName: 'Coded hola',
      bvn: '20203212',
      email: 'codedhola2000@gmail.com,',
      birthDate: '2021-11-07',
      occupation: 'Engineer',
      businessCategory: 'Engineering',
      additionalInfo: '',
    },
    channel: 'vfd',
    accountType: 'corporate',
    meansOfId: [''],
    utilityBill: '',
    reason: 'cross-border',
    paymentFlowDescription: 'NGN to NGN',
    monthlyVolume: '233',
    entityName: 'Coded hola',
    attachments: '',
  };